//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.LoreServiseRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoreServiseRef.IServiseForServer", CallbackContract=typeof(Client.LoreServiseRef.IServiseForServerCallback))]
    public interface IServiseForServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiseForServer/Connect", ReplyAction="http://tempuri.org/IServiseForServer/ConnectResponse")]
        void Connect(string connectlogin, string connectpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiseForServer/Connect", ReplyAction="http://tempuri.org/IServiseForServer/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string connectlogin, string connectpassword);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/Disconnect")]
        void Disconnect(string connectlogin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(string connectlogin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/SendStringMessage")]
        void SendStringMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/SendStringMessage")]
        System.Threading.Tasks.Task SendStringMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/CheckHashAndLog")]
        void CheckHashAndLog(string chekingString, string login);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/CheckHashAndLog")]
        System.Threading.Tasks.Task CheckHashAndLogAsync(string chekingString, string login);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/RegIn")]
        void RegIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/RegIn")]
        System.Threading.Tasks.Task RegInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiseForServer/ResiveIp", ReplyAction="http://tempuri.org/IServiseForServer/ResiveIpResponse")]
        string ResiveIp(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiseForServer/ResiveIp", ReplyAction="http://tempuri.org/IServiseForServer/ResiveIpResponse")]
        System.Threading.Tasks.Task<string> ResiveIpAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/ReciveConfigData")]
        void ReciveConfigData(string[] dataFromConfig);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/ReciveConfigData")]
        System.Threading.Tasks.Task ReciveConfigDataAsync(string[] dataFromConfig);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiseForServerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/ReceiveLoreMessage")]
        void ReceiveLoreMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/DoYouLog")]
        void DoYouLog(bool IsLoggin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiseForServer/SetIpInTextbox")]
        void SetIpInTextbox(string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiseForServerChannel : Client.LoreServiseRef.IServiseForServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiseForServerClient : System.ServiceModel.DuplexClientBase<Client.LoreServiseRef.IServiseForServer>, Client.LoreServiseRef.IServiseForServer {
        
        public ServiseForServerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiseForServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiseForServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiseForServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiseForServerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string connectlogin, string connectpassword) {
            base.Channel.Connect(connectlogin, connectpassword);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string connectlogin, string connectpassword) {
            return base.Channel.ConnectAsync(connectlogin, connectpassword);
        }
        
        public void Disconnect(string connectlogin) {
            base.Channel.Disconnect(connectlogin);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string connectlogin) {
            return base.Channel.DisconnectAsync(connectlogin);
        }
        
        public void SendStringMessage(string message) {
            base.Channel.SendStringMessage(message);
        }
        
        public System.Threading.Tasks.Task SendStringMessageAsync(string message) {
            return base.Channel.SendStringMessageAsync(message);
        }
        
        public void CheckHashAndLog(string chekingString, string login) {
            base.Channel.CheckHashAndLog(chekingString, login);
        }
        
        public System.Threading.Tasks.Task CheckHashAndLogAsync(string chekingString, string login) {
            return base.Channel.CheckHashAndLogAsync(chekingString, login);
        }
        
        public void RegIn(string username, string password) {
            base.Channel.RegIn(username, password);
        }
        
        public System.Threading.Tasks.Task RegInAsync(string username, string password) {
            return base.Channel.RegInAsync(username, password);
        }
        
        public string ResiveIp(string login) {
            return base.Channel.ResiveIp(login);
        }
        
        public System.Threading.Tasks.Task<string> ResiveIpAsync(string login) {
            return base.Channel.ResiveIpAsync(login);
        }
        
        public void ReciveConfigData(string[] dataFromConfig) {
            base.Channel.ReciveConfigData(dataFromConfig);
        }
        
        public System.Threading.Tasks.Task ReciveConfigDataAsync(string[] dataFromConfig) {
            return base.Channel.ReciveConfigDataAsync(dataFromConfig);
        }
    }
}
